world:addCollisionClass('Wall')
world:addCollisionClass('Player')
world:addCollisionClass('Enemy', {ignores = {'Enemy', 'Player'}})
world:addCollisionClass('Weapon', {ignores = {'Player', 'Wall', 'Enemy'}})
world:setQueryDebugDrawing(true)
