return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 22,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 5,
  nextobjectid = 979,
  properties = {},
  tilesets = {
    {
      name = "tiles-overworld",
      firstgid = 1,
      filename = "../../../../../tiled/new_tilesets/tiles-overworld.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 36,
      image = "../../graphics/tiles-overworld.png",
      imagewidth = 288,
      imageheight = 128,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 576,
      tiles = {}
    },
    {
      name = "collide8",
      firstgid = 577,
      filename = "../../../../../tiled/new_tilesets/collide8.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../../graphics/collider8.png",
      imagewidth = 8,
      imageheight = 8,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 2,
      name = "Water_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 1,
      name = "Ground_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5,
        0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0, 5, 5, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 3,
      name = "Collision_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 0, 0, 0, 0, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88,
        123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 0, 0, 0, 0, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124,
        87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 0, 0, 0, 0, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88, 87, 88,
        123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 0, 0, 0, 0, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124, 123, 124,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 88,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 123, 124,
        87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 0, 0, 87, 88, 0, 0, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 0, 0, 87, 88,
        123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 0, 0, 123, 124, 0, 0, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 0, 0, 123, 124,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0,
        123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 0, 0, 87, 88, 0, 0, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 0, 0, 87, 88,
        123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 0, 0, 123, 124, 0, 0, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 0, 0, 123, 124,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 88,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 123, 124,
        87, 88, 87, 88, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88,
        123, 124, 123, 124, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124,
        87, 88, 87, 88, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88, 0, 0, 87, 88,
        123, 124, 123, 124, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124, 0, 0, 123, 124
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Collide",
      visible = false,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 612,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 613,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 616,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 625,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 626,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 629,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 630,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 651,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 652,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 653,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 654,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 655,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 657,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 658,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 676,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 677,
          name = "",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 678,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 679,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 683,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 684,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 687,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 688,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 723,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 727,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 728,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 731,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 732,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 750,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 751,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 752,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 757,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 766,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 767,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 768,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 769,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 770,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 771,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 772,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 773,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 774,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 775,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 776,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 777,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 778,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 779,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 780,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 785,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 786,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 787,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 788,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 789,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 790,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 791,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 792,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 793,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 794,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 795,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 798,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 799,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 800,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 837,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 838,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 839,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 840,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 841,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 842,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 843,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 844,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 845,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 846,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 847,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 848,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 849,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 850,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 851,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 852,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 853,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 854,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 855,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 856,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 857,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 858,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 859,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 860,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 861,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 862,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 863,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 864,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 865,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 866,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 867,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 868,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 869,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 870,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 871,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 872,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 873,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 874,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 875,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 876,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 877,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 878,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 879,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 880,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 881,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 882,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 883,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 884,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 885,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 886,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 889,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 890,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 893,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 894,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 895,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 896,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 897,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 898,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 899,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 900,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 901,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 902,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 903,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 904,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 905,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 906,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 907,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 908,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 909,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 910,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 911,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 912,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 913,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 914,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 915,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 8,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 916,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 0,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 917,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 0,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 918,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 919,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 0,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 920,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 8,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 921,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 922,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 923,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 924,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 925,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 926,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 927,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 928,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 929,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 930,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 931,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 932,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 933,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 934,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 935,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 936,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 937,
          name = "",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 938,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 939,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 940,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 941,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 942,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 943,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 944,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 945,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 946,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 947,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 948,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 949,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 950,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 951,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 952,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 953,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 954,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 955,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 956,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 957,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 958,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 959,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 960,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 961,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 962,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 963,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 964,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 965,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 966,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 967,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 968,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 969,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 970,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 971,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 972,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 973,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 974,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 975,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 976,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 977,
          name = "",
          type = "",
          shape = "rectangle",
          x = 248,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 978,
          name = "",
          type = "",
          shape = "rectangle",
          x = 248,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
