return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 22,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 5,
  nextobjectid = 1176,
  properties = {},
  tilesets = {
    {
      name = "tiles-overworld",
      firstgid = 1,
      filename = "../../../../../tiled/new_tilesets/tiles-overworld.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 36,
      image = "../../graphics/tiles-overworld.png",
      imagewidth = 288,
      imageheight = 128,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 576,
      tiles = {}
    },
    {
      name = "collide8",
      firstgid = 577,
      filename = "../../../../../tiled/new_tilesets/collide8.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../../graphics/collider8.png",
      imagewidth = 8,
      imageheight = 8,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 2,
      name = "Water_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 1,
      name = "Ground_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0,
        5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 3,
      name = "Collision_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232,
        267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268,
        231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 0, 0, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232,
        267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 0, 0, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 229, 230, 231, 232,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 265, 266, 267, 268,
        0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 4, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 229, 230,
        0, 0, 0, 0, 0, 0, 39, 40, 39, 40, 39, 40, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 265, 266,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 40, 39, 40, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 4, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 39, 40, 39, 40, 39, 40, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 40, 39, 40, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 4, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 157, 158,
        0, 0, 0, 0, 0, 0, 39, 40, 39, 40, 39, 40, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 193, 194,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 157, 158, 231, 232,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 193, 194, 267, 268,
        159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 159, 160, 0, 0, 0, 0, 231, 232, 231, 232,
        195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 195, 196, 0, 0, 0, 0, 267, 268, 267, 268,
        231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 231, 232, 0, 0, 0, 0, 231, 232, 231, 232,
        267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 267, 268, 0, 0, 0, 0, 267, 268, 267, 268
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Collide",
      visible = false,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 979,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 980,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 981,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 982,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 983,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 984,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 985,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 986,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 987,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 988,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 989,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 990,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 992,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 993,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 995,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 996,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 997,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 998,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 999,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1000,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1001,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1002,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1003,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1004,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1005,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1006,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1007,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1008,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1009,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1010,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1027,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1028,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1029,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1030,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1031,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1032,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1033,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1034,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1035,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1036,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1037,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1038,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1039,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1040,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1041,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1042,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1043,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1044,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1045,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1046,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1047,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1048,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1049,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1050,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1051,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1052,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1053,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1054,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1055,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1056,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1057,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1058,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1059,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1060,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1061,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1068,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1069,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1070,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1072,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1073,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1074,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1075,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1077,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1078,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1079,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1082,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1084,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1085,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1086,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1087,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1088,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1089,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1090,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1091,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1092,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1095,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1097,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1099,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 184,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 248,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 248,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1162,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1163,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1168,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1169,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 577,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
