return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 22,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 8,
  nextobjectid = 570,
  properties = {},
  tilesets = {
    {
      name = "dungeon_tileset",
      firstgid = 1,
      filename = "../../../../../tiled/new_tilesets/dungeon_tileset.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "../../graphics/dungeon_tilesets.png",
      imagewidth = 512,
      imageheight = 128,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    },
    {
      name = "collide8",
      firstgid = 1025,
      filename = "../../../../../tiled/new_tilesets/collide8.tsx",
      tilewidth = 8,
      tileheight = 8,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../../graphics/collider8.png",
      imagewidth = 8,
      imageheight = 8,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 8,
        height = 8
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 1,
      name = "Ground_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 0, 0, 427, 428, 427, 428, 0, 0, 427, 428, 427, 428, 0, 0, 427, 428, 427, 428, 0, 0, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 0, 0, 491, 492, 491, 492, 0, 0, 491, 492, 491, 492, 0, 0, 491, 492, 491, 492, 0, 0, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 0, 0, 427, 428, 0, 0, 427, 428, 427, 428, 427, 428, 427, 428, 0, 0, 427, 428, 0, 0, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 0, 0, 491, 492, 0, 0, 491, 492, 491, 492, 491, 492, 491, 492, 0, 0, 491, 492, 0, 0, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 0, 0, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 0, 0, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 0, 0, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 0, 0, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 0, 0, 0, 0, 0, 0, 0, 0, 427, 428, 427, 428, 0, 0, 0, 0, 0, 0, 0, 0, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 0, 0, 0, 0, 0, 0, 0, 0, 491, 492, 491, 492, 0, 0, 0, 0, 0, 0, 0, 0, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 427, 428, 0, 0, 0, 0,
        0, 0, 0, 0, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 491, 492, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 3,
      name = "Collision_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 803, 815, 815, 809, 815, 815, 807, 815, 809, 815, 815, 807, 815, 815, 815, 815, 872, 815, 815, 874, 815, 872, 815, 815, 874, 815, 815, 868, 0, 0,
        0, 0, 816, 803, 815, 815, 807, 815, 809, 815, 815, 807, 815, 809, 815, 815, 815, 815, 874, 815, 872, 815, 815, 874, 815, 872, 815, 815, 868, 880, 0, 0,
        0, 0, 816, 816, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 880, 880, 0, 0,
        0, 0, 687, 805, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 870, 752, 0, 0,
        0, 0, 805, 816, 0, 0, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 681, 682, 0, 0, 880, 870, 0, 0,
        0, 0, 816, 687, 0, 0, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 745, 746, 0, 0, 752, 880, 0, 0,
        0, 0, 687, 805, 0, 0, 681, 682, 0, 0, 0, 0, 555, 556, 0, 0, 0, 0, 683, 684, 0, 0, 0, 0, 681, 682, 0, 0, 870, 752, 0, 0,
        0, 0, 610, 611, 0, 0, 745, 746, 0, 0, 0, 0, 619, 620, 0, 0, 0, 0, 747, 748, 0, 0, 0, 0, 745, 746, 0, 0, 880, 880, 0, 0,
        0, 0, 417, 428, 0, 0, 681, 682, 0, 0, 555, 556, 0, 0, 0, 0, 0, 0, 0, 0, 683, 684, 0, 0, 681, 682, 0, 0, 880, 880, 0, 0,
        0, 0, 417, 492, 0, 0, 745, 746, 0, 0, 619, 620, 0, 0, 0, 0, 0, 0, 0, 0, 747, 748, 0, 0, 745, 746, 0, 0, 880, 880, 0, 0,
        0, 0, 547, 548, 0, 0, 681, 682, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 681, 682, 0, 0, 880, 880, 0, 0,
        0, 0, 751, 869, 0, 0, 745, 746, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 745, 746, 0, 0, 806, 688, 0, 0,
        0, 0, 816, 751, 0, 0, 681, 682, 681, 682, 681, 682, 681, 682, 0, 0, 0, 0, 681, 682, 681, 682, 681, 682, 681, 682, 0, 0, 688, 880, 0, 0,
        0, 0, 869, 816, 0, 0, 745, 746, 745, 746, 745, 746, 745, 746, 0, 0, 0, 0, 745, 746, 745, 746, 745, 746, 745, 746, 0, 0, 880, 806, 0, 0,
        0, 0, 751, 869, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 806, 688, 0, 0,
        0, 0, 816, 816, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 880, 880, 0, 0,
        0, 0, 816, 867, 879, 879, 871, 879, 873, 879, 879, 871, 879, 873, 879, 879, 879, 879, 810, 879, 808, 879, 879, 810, 879, 808, 879, 879, 804, 880, 0, 0,
        0, 0, 867, 879, 879, 873, 879, 879, 871, 879, 873, 879, 879, 871, 879, 879, 879, 879, 808, 879, 879, 810, 879, 808, 879, 879, 810, 879, 879, 804, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 22,
      id = 5,
      name = "Wall_layer",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940,
        940, 929, 164, 164, 164, 801, 164, 164, 164, 164, 801, 164, 164, 813, 164, 164, 164, 164, 878, 164, 164, 866, 164, 164, 164, 164, 866, 164, 164, 164, 993, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 685, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 750, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 811, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 876, 940,
        940, 546, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 546, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 546, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 546, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 812, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 749, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 686, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 164, 940,
        940, 993, 164, 164, 164, 865, 164, 164, 164, 164, 865, 164, 164, 877, 164, 164, 164, 164, 814, 164, 164, 802, 164, 164, 164, 164, 802, 164, 164, 164, 929, 940,
        940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940, 940
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Collide",
      visible = false,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "",
          shape = "rectangle",
          x = -8,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 504,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 526,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 527,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 530,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 531,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 534,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 536,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 539,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 543,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 554,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 559,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 560,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 563,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 565,
          name = "",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        },
        {
          id = 569,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 1025,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Door",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 316,
          name = "left",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 411,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
